name: SpellBend
version: '${project.version}'
main: me.chriss99.spellbend.SpellBend
api-version: 1.17
authors: [ Chriss99 ]
description: remaking the skript game as a java plugin
depend:
  - ProtocolLib
commands:
  test:
    permission: spellbend.test.all
  reflectTest:
    permission: spellbend.test.all
  shop:
    permission: spellbend.shop
permissions:
  spellbend.test.all:
    default: op
  spellbend.shop:
    default: true